# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "techisfun/raspberry-pi-desktop"
  config.vm.box_version = "1.0.0"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
  end
  
  # Update apt
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
     apt-get upgrade -y
  SHELL
end
