# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "gvfoster/raspbian"

  # Prevent SharedFoldersEnableSymlinksCreate errors
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
  end
  
  # Update apt
  #config.vm.provision "shell", inline: <<-SHELL
  #  export DEBIAN_FRONTEND=noninteractive
  #  apt-get update -y
  #  apt-get upgrade -y
  #SHELL
end
