---
name: Build

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: "0 5 * * 4"

jobs:

  provision-ubuntu-on-macos:
    name: Provision Ubuntu VM on Macos host
    runs-on: macos-10.15

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Install homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Virtualbox
        run: brew install virtualbox

      - name: Install vagrant
        run: brew install vagrant
        
      - name: Show Vagrant version
        run: vagrant --version

      - name: Provision Ubuntu VM
        run: cd vagrant-ubuntu && vagrant up --debug
        
      - name: ssh into box after boot
        run: vagrant ssh -c "echo 'hello world!'"

  provision-ubuntu-on-ubuntu:
    name: Provision Ubuntu VM on Ubuntu host
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Update apt
        run: sudo apt-get update

      - name: Install Virtualbox
        run: sudo apt-get install virtualbox -y

      - name: Install vagrant
        run: sudo apt-get install vagrant -y
      
      - name: Provision Ubuntu VM
        run: cd vagrant-ubuntu && vagrant up --debug

  provision-raspbian-on-macos:
    name: Provision Raspbian VM on MacOS host
    runs-on: macos-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Install homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Virtualbox
        run: brew install virtualbox

      - name: Install vagrant
        run: brew install vagrant

      #- name: Cache Vagrant boxes
      #  uses: actions/cache@v2
      #  with:
      #    path: ~/.vagrant.d/boxes
      #    key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
      #    restore-keys: |
      #      ${{ runner.os }}-vagrant-

      - name: Run vagrant up
        run: cd vagrant-raspbian && vagrant up --debug

      - name: Run ssh connection
        run: vagrant ssh -c "echo 'Hello world!'"
