---
name: Build

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: "0 5 * * 4"

jobs:

  provision-ubuntu-on-macos:
    name: Provision Ubuntu VM on Macos host
    runs-on: macos-10.15

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Install homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Virtualbox
        run: brew install virtualbox

      - name: Install vagrant
        run: brew install vagrant
        
      - name: Show Vagrant version
        run: vagrant --version

      - name: Provision Ubuntu VM
        run: vagrant up --debug
        working-directory: vagrant-ubuntu
        
      - name: ssh into box after boot
        run: vagrant ssh -c "echo 'hello world!'"
        working-directory: vagrant-ubuntu
